name: Test and update master

on:
  push:
    branches: ["main"]

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - name: Get project name from pyproject.toml
        id: get_name
        run: |
          CMD='import toml; print(toml.load("pyproject.toml")["tool"]["poetry"]["name"])'
          echo "NAME=$(python -c ${CMD})" >> $GITHUB_ENV

      - name: Get project version
        id: get_version
        run: |
          CMD="import pkg_resources; print(pkg_resources.get_distribution('${{ env.NAME }}').version)""
          echo "VERSION=$(python -c ${CMD})" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
