name: Test and update master

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
  push:
    branches: ["develop"]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        runs-on: ["macos-latest", "ubuntu-latest"]
        cmd: ["mypy", "pytest", "nbmake"]

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and test
        run: |
          pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          make install
          make ${{ matrix.cmd }}

  push-to-main:
    needs: test
    runs-on: "ubuntu-latest"
    steps:
      - name: Push to main if tests pass
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          tags: true
